language: julia

os: osx
julia: 1.0

notifications:
  email: true

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("SplittingOperators")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("SplittingOperators")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: osx
      script:
        - julia -e 'using Pkg; Pkg.instantiate()'
        - julia docs/make.jl
      after_success: skip
