name = "SplittingOperators"
uuid = "f32125ac-d6a3-11e8-0cad-b1bde0c48ea2"
authors = ["Pierre Navaro <pierre.navaro@math.cnrs.fr>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
