name = "SplittingOperators"
uuid = "f32125ac-d6a3-11e8-0cad-b1bde0c48ea2"
authors = ["Pierre Navaro <pierre.navaro@math.cnrs.fr>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
